########################################################################
## Travis CI config for SoapyOsmo
##
## * installs RTL, Osmo, and Airspy
## * installs SoapySDR from source
## * confirms build and install
## * no unit tests
########################################################################

sudo: required
dist: trusty

language: cpp
compiler: gcc

env:
  global:
    - INSTALL_PREFIX=/usr/local
    - SOAPY_SDR_BRANCH=master
    - RTL_SDR_BRANCH=v0.5.3
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

before_install:
  # regular ubuntu packages
  - sudo add-apt-repository main
  - sudo add-apt-repository universe

  # driver development files from ppa
  - sudo add-apt-repository -y ppa:myriadrf/drivers

  # update after package changes
  - sudo apt-get update

install:
  #boost development files
  - sudo apt-get install -qq libboost-all-dev

  #sdr development files
  - sudo apt-get install -qq libosmosdr-dev libmirisdr-dev libairspy-dev

  # install SoapySDR from source
  - git clone https://github.com/pothosware/SoapySDR.git
  - pushd SoapySDR
  - git checkout ${SOAPY_SDR_BRANCH}
  - mkdir build && cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DENABLE_PYTHON=OFF -DENABLE_PYTHON3=OFF
  - make && sudo make install
  - popd

script:
  - mkdir build && cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make && sudo make install
  # print info about the install
  - export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}
  - export PATH=${INSTALL_PREFIX}/bin:${PATH}
  - SoapySDRUtil --info
