########################################################################
## Travis CI config for SoapyOsmo
##
## * installs SoapySDR from source
## * installs RTL SDR from source
## * confirms build and install
## * no unit tests
########################################################################

language: cpp
compiler: gcc

env:
  global:
    - INSTALL_PREFIX=/usr/local
    - SOAPY_SDR_BRANCH=master
    - RTL_SDR_BRANCH=v0.5.3
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

install:
  - sudo apt-get install -qq cmake libusb-1.0-0-dev libboost-all-dev
  # install SoapySDR from source
  - git clone https://github.com/pothosware/SoapySDR.git
  - pushd SoapySDR
  - git checkout ${SOAPY_SDR_BRANCH}
  - mkdir build && cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make && sudo make install
  - popd
  # install rtlsdr from source
  - git clone git://git.osmocom.org/rtl-sdr.git
  - pushd rtl-sdr
  - git checkout ${RTL_SDR_BRANCH}
  - mkdir build && cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make && sudo make install
  - popd

script:
  - mkdir build && cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make && sudo make install
  # print info about the install
  - export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}
  - export PATH=${INSTALL_PREFIX}/bin:${PATH}
  - SoapySDRUtil --info
